import { Stock } from './types';

function generateHistory(startPrice: number, days: number = 30): { date: string; close: number }[] {
    const history = [];
    let currentPrice = startPrice;
    const now = new Date();

    for (let i = days; i > 0; i--) {
        const date = new Date(now);
        date.setDate(date.getDate() - i);

        // Random walk
        const change = (Math.random() - 0.5) * (startPrice * 0.05);
        currentPrice += change;

        history.push({
            date: date.toISOString().split('T')[0],
            close: Number(currentPrice.toFixed(2)),
        });
    }
    return history;
}

export const MOCK_STOCKS: Stock[] = [
    {
        ticker: 'AAPL',
        name: 'Apple Inc.',
        price: 175.43,
        change: 1.25,
        changesPercentage: 0.72,
        marketCap: 2700000000000,
        pe: 28.5,
        sector: 'Technology',
        industry: 'Consumer Electronics',
        beta: 1.2,
        description: 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories.',
        priceHistory: generateHistory(170),
        dividendYield: 0.5,
        high52Week: 198.23,
        low52Week: 124.17
    },
    {
        ticker: 'MSFT',
        name: 'Microsoft Corporation',
        price: 330.11,
        change: -2.10,
        changesPercentage: -0.63,
        marketCap: 2500000000000,
        pe: 32.1,
        sector: 'Technology',
        industry: 'Software - Infrastructure',
        beta: 0.9,
        description: 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide.',
        priceHistory: generateHistory(335),
        dividendYield: 0.8,
        high52Week: 366.78,
        low52Week: 213.43
    },
    {
        ticker: 'GOOGL',
        name: 'Alphabet Inc.',
        price: 135.20,
        change: 0.50,
        changesPercentage: 0.37,
        marketCap: 1700000000000,
        pe: 25.4,
        sector: 'Technology',
        industry: 'Internet Content & Information',
        beta: 1.05,
        description: 'Alphabet Inc. offers various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America.',
        priceHistory: generateHistory(130),
        dividendYield: 0,
        high52Week: 142.38,
        low52Week: 83.45
    },
    {
        ticker: 'AMZN',
        name: 'Amazon.com Inc.',
        price: 145.30,
        change: 3.10,
        changesPercentage: 2.18,
        marketCap: 1500000000000,
        pe: 60.5,
        sector: 'Consumer Cyclical',
        industry: 'Internet Retail',
        beta: 1.3,
        description: 'Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally.',
        priceHistory: generateHistory(140),
        dividendYield: 0,
        high52Week: 151.28,
        low52Week: 81.43
    },
    {
        ticker: 'TSLA',
        name: 'Tesla Inc.',
        price: 240.50,
        change: -5.60,
        changesPercentage: -2.28,
        marketCap: 760000000000,
        pe: 70.2,
        sector: 'Consumer Cyclical',
        industry: 'Auto Manufacturers',
        beta: 2.1,
        description: 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems.',
        priceHistory: generateHistory(250),
        dividendYield: 0,
        high52Week: 299.29,
        low52Week: 101.81
    },
    {
        ticker: 'NVDA',
        name: 'NVIDIA Corporation',
        price: 460.15,
        change: 10.50,
        changesPercentage: 2.33,
        marketCap: 1150000000000,
        pe: 110.5,
        sector: 'Technology',
        industry: 'Semiconductors',
        beta: 1.7,
        description: 'NVIDIA Corporation provides graphics, compute and networking solutions in the United States, Taiwan, China, and internationally.',
        priceHistory: generateHistory(440),
        dividendYield: 0.04,
        high52Week: 502.66,
        low52Week: 108.13
    },
    {
        ticker: 'META',
        name: 'Meta Platforms Inc.',
        price: 315.60,
        change: 4.20,
        changesPercentage: 1.35,
        marketCap: 810000000000,
        pe: 24.8,
        sector: 'Technology',
        industry: 'Internet Content & Information',
        beta: 1.4,
        description: 'Meta Platforms, Inc. engages in the development of products that enable people to connect and share with friends and family.',
        priceHistory: generateHistory(300),
        dividendYield: 0,
        high52Week: 325.35,
        low52Week: 88.09
    },
    {
        ticker: 'BRK.B',
        name: 'Berkshire Hathaway Inc.',
        price: 355.40,
        change: 1.10,
        changesPercentage: 0.31,
        marketCap: 780000000000,
        pe: 9.5,
        sector: 'Financial Services',
        industry: 'Insurance - Diversified',
        beta: 0.85,
        description: 'Berkshire Hathaway Inc. engages in the insurance, freight rail transportation, and utility businesses.',
        priceHistory: generateHistory(350),
        dividendYield: 0,
        high52Week: 373.34,
        low52Week: 292.45
    },
    {
        ticker: 'LLY',
        name: 'Eli Lilly and Company',
        price: 580.90,
        change: -2.30,
        changesPercentage: -0.39,
        marketCap: 550000000000,
        pe: 85.0,
        sector: 'Healthcare',
        industry: 'Drug Manufacturers - General',
        beta: 0.35,
        description: 'Eli Lilly and Company discovers, develops, manufactures, and markets human pharmaceuticals worldwide.',
        priceHistory: generateHistory(570),
        dividendYield: 0.9,
        high52Week: 601.54,
        low52Week: 309.20
    },
    {
        ticker: 'JPM',
        name: 'JPMorgan Chase & Co.',
        price: 155.60,
        change: 0.80,
        changesPercentage: 0.52,
        marketCap: 450000000000,
        pe: 10.2,
        sector: 'Financial Services',
        industry: 'Banks - Diversified',
        beta: 1.1,
        description: 'JPMorgan Chase & Co. operates as a financial services company worldwide.',
        priceHistory: generateHistory(150),
        dividendYield: 2.7,
        high52Week: 159.38,
        low52Week: 123.11
    },
    {
        ticker: 'XOM',
        name: 'Exxon Mobil Corporation',
        price: 115.30,
        change: 1.50,
        changesPercentage: 1.32,
        marketCap: 460000000000,
        pe: 11.5,
        sector: 'Energy',
        industry: 'Oil & Gas Integrated',
        beta: 1.1,
        description: 'Exxon Mobil Corporation engages in the exploration and production of crude oil and natural gas in the United States and internationally.',
        priceHistory: generateHistory(110),
        dividendYield: 3.2,
        high52Week: 120.70,
        low52Week: 98.45
    },
    {
        ticker: 'UNH',
        name: 'UnitedHealth Group',
        price: 490.20,
        change: -1.50,
        changesPercentage: -0.30,
        marketCap: 450000000000,
        pe: 22.0,
        sector: 'Healthcare',
        industry: 'Healthcare Plans',
        beta: 0.6,
        description: 'UnitedHealth Group Incorporated operates as a diversified health care company in the United States.',
        priceHistory: generateHistory(495),
        dividendYield: 1.5,
        high52Week: 558.10,
        low52Week: 445.68
    },
    {
        ticker: 'V',
        name: 'Visa Inc.',
        price: 245.80,
        change: 1.80,
        changesPercentage: 0.74,
        marketCap: 510000000000,
        pe: 31.0,
        sector: 'Financial Services',
        industry: 'Credit Services',
        beta: 0.95,
        description: 'Visa Inc. operates as a payments technology company worldwide.',
        priceHistory: generateHistory(240),
        dividendYield: 0.8,
        high52Week: 250.06,
        low52Week: 198.88
    },
    {
        ticker: 'JNJ',
        name: 'Johnson & Johnson',
        price: 160.50,
        change: 0.20,
        changesPercentage: 0.12,
        marketCap: 390000000000,
        pe: 15.5,
        sector: 'Healthcare',
        industry: 'Drug Manufacturers - General',
        beta: 0.55,
        description: 'Johnson & Johnson researches and develops, manufactures, and sells various products in the healthcare field worldwide.',
        priceHistory: generateHistory(160),
        dividendYield: 2.9,
        high52Week: 181.04,
        low52Week: 150.11
    },
    {
        ticker: 'WMT',
        name: 'Walmart Inc.',
        price: 162.40,
        change: -0.50,
        changesPercentage: -0.31,
        marketCap: 430000000000,
        pe: 25.0,
        sector: 'Consumer Defensive',
        industry: 'Discount Stores',
        beta: 0.5,
        description: 'Walmart Inc. engages in the operation of retail, wholesale, and other units worldwide.',
        priceHistory: generateHistory(160),
        dividendYield: 1.4,
        high52Week: 169.94,
        low52Week: 136.09
    },
    {
        ticker: 'PG',
        name: 'Procter & Gamble',
        price: 152.10,
        change: 0.40,
        changesPercentage: 0.26,
        marketCap: 360000000000,
        pe: 24.5,
        sector: 'Consumer Defensive',
        industry: 'Household & Personal Products',
        beta: 0.4,
        description: 'The Procter & Gamble Company provides branded consumer packaged goods to consumers in North and Latin America, Europe, the Asia Pacific, Greater China, and India, the Middle East, and Africa.',
        priceHistory: generateHistory(150),
        dividendYield: 2.3,
        high52Week: 158.38,
        low52Week: 135.37
    },
    {
        ticker: 'MA',
        name: 'Mastercard',
        price: 410.20,
        change: 3.50,
        changesPercentage: 0.86,
        marketCap: 385000000000,
        pe: 35.0,
        sector: 'Financial Services',
        industry: 'Credit Services',
        beta: 1.0,
        description: 'Mastercard Incorporated serves as a technology company in the global payments industry.',
        priceHistory: generateHistory(400),
        dividendYield: 0.6,
        high52Week: 417.89,
        low52Week: 340.20
    },
    {
        ticker: 'CVX',
        name: 'Chevron Corporation',
        price: 168.30,
        change: 2.10,
        changesPercentage: 1.26,
        marketCap: 315000000000,
        pe: 10.8,
        sector: 'Energy',
        industry: 'Oil & Gas Integrated',
        beta: 1.2,
        description: 'Chevron Corporation engages in integrated energy and chemicals operations worldwide.',
        priceHistory: generateHistory(165),
        dividendYield: 3.9,
        high52Week: 189.68,
        low52Week: 150.34
    },
    {
        ticker: 'KO',
        name: 'Coca-Cola Company',
        price: 58.40,
        change: 0.10,
        changesPercentage: 0.17,
        marketCap: 250000000000,
        pe: 23.0,
        sector: 'Consumer Defensive',
        industry: 'Beverages - Non-Alcoholic',
        beta: 0.6,
        description: 'The Coca-Cola Company, a beverage company, manufactures, markets, and sells various non-alcoholic beverages worldwide.',
        priceHistory: generateHistory(58),
        dividendYield: 3.1,
        high52Week: 64.99,
        low52Week: 55.85
    },
    {
        ticker: 'PEP',
        name: 'PepsiCo Inc.',
        price: 178.50,
        change: -0.20,
        changesPercentage: -0.11,
        marketCap: 245000000000,
        pe: 22.5,
        sector: 'Consumer Defensive',
        industry: 'Beverages - Non-Alcoholic',
        beta: 0.6,
        description: 'PepsiCo, Inc. manufactures, markets, distributes, and sells various beverages and convenient foods worldwide.',
        priceHistory: generateHistory(180),
        dividendYield: 2.7,
        high52Week: 196.88,
        low52Week: 160.98
    },
    // Add some smaller/different stocks for variety
    {
        ticker: 'PLTR',
        name: 'Palantir Technologies',
        price: 18.50,
        change: 0.90,
        changesPercentage: 5.11,
        marketCap: 40000000000,
        pe: null, // Loss making historically or very high
        sector: 'Technology',
        industry: 'Software - Infrastructure',
        beta: 2.5,
        description: 'Palantir Technologies Inc. builds and deploys software platforms for the intelligence community in the United States to assist in counterterrorism investigations and operations.',
        priceHistory: generateHistory(16),
        dividendYield: 0,
        high52Week: 21.85,
        low52Week: 7.20
    },
    {
        ticker: 'ZOMATO',
        name: 'Zomato Ltd',
        price: 1.50,
        change: 0.05,
        changesPercentage: 3.4,
        marketCap: 12000000000,
        pe: 150.0,
        sector: 'Consumer Cyclical',
        industry: 'Internet Retail',
        beta: 1.5,
        description: 'Zomato Limited operates as an internet portal that connects users, restaurant partners, and delivery partners.',
        priceHistory: generateHistory(1.4),
        dividendYield: 0,
        high52Week: 2.10,
        low52Week: 0.80
    }
];
